// Package dnsmasqcfg writes a dnsmasq.d snippet that delegates manual-allow
// and extension domains to dnsmasq's native ipset= directive. dnsmasq then
// populates the kernel ipset synchronously during DNS resolution — including
// walking CNAME chains and adding all final A-records — which closes the
// timing race ladon's tail-and-reconcile loop can't ever win for the very
// first TCP SYN after a fresh resolve.
package dnsmasqcfg

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// Path is where the snippet lives. dnsmasq picks up everything in
// /etc/dnsmasq.d/ that matches its include glob (set in dnsmasq.conf).
// A var (not const) so tests can point it at a temp file.
var Path = "/etc/dnsmasq.d/ladon-manual.conf"

// Write produces the snippet at Path. Atomic via tmp+rename so dnsmasq
// never observes a half-written file. Empty domains list still writes a
// stub — keeps file present for operator visibility, dnsmasq treats it
// as a no-op include. Returns changed=false without touching the file when
// the snippet already matches on disk, so the caller can skip the dnsmasq
// restart (see the crash-loop guard below).
func Write(ipsetName string, domains []string) (changed bool, err error) {
	if ipsetName == "" {
		return false, fmt.Errorf("dnsmasqcfg: empty ipset name")
	}
	// Dedup + sort for stable diff. Operators reading the file want
	// alphabetical order, not insertion order.
	uniq := make(map[string]struct{}, len(domains))
	for _, d := range domains {
		d = strings.ToLower(strings.TrimSpace(strings.TrimRight(d, ".")))
		if d == "" {
			continue
		}
		uniq[d] = struct{}{}
	}
	sorted := make([]string, 0, len(uniq))
	for d := range uniq {
		sorted = append(sorted, d)
	}
	sort.Strings(sorted)

	var sb strings.Builder
	sb.WriteString("# Generated by ladon — do not edit.\n")
	sb.WriteString("# Source: manual-allow.txt + enabled extensions.\n")
	sb.WriteString("# dnsmasq populates the ipset synchronously during DNS resolution,\n")
	sb.WriteString("# walking CNAME chains, so the first TCP SYN after a fresh resolve\n")
	sb.WriteString("# already finds its destination IP in the kernel set.\n\n")
	for _, d := range sorted {
		fmt.Fprintf(&sb, "ipset=/%s/%s\n", d, ipsetName)
	}
	next := sb.String()

	// Skip the rewrite (and the dnsmasq bounce the caller does on change) when
	// the snippet already matches on disk. Ladon writes this on every start, so
	// without the guard a crash-loop restarts dnsmasq every few seconds and
	// flaps DNS for the whole network — the content is identical each time.
	if cur, rerr := os.ReadFile(Path); rerr == nil && string(cur) == next {
		return false, nil
	}

	dir := filepath.Dir(Path)
	tmp, err := os.CreateTemp(dir, ".ladon-manual.conf.*")
	if err != nil {
		return false, fmt.Errorf("create temp: %w", err)
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)

	if _, err := tmp.WriteString(next); err != nil {
		tmp.Close()
		return false, fmt.Errorf("write temp: %w", err)
	}
	if err := tmp.Chmod(0o644); err != nil {
		tmp.Close()
		return false, fmt.Errorf("chmod temp: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return false, fmt.Errorf("close temp: %w", err)
	}
	if err := os.Rename(tmpPath, Path); err != nil {
		return false, fmt.Errorf("rename %s: %w", Path, err)
	}
	return true, nil
}

// Restart bounces dnsmasq so it re-reads /etc/dnsmasq.d/*.conf. Required
// because SIGHUP (systemctl reload) only re-reads /etc/resolv.conf and
// /etc/hosts — the `ipset=` directives ladon writes here are parsed at
// startup and ignored on reload. Hardcoded to the systemd service name;
// ladon only supports systemd-managed dnsmasq.
//
// Cost: ~100ms of DNS unavailability per ladon startup. Acceptable
// because (a) dnsmasq is stateless and comes back instantly, (b) this
// only runs at ladon start, not per-query, (c) eliminating the manual
// `systemctl restart dnsmasq` step after editing manual-allow / extensions
// is worth the blip.
func Restart(ctx context.Context) error {
	cmd := exec.CommandContext(ctx, "systemctl", "restart", "dnsmasq")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemctl restart dnsmasq: %w (output: %s)", err, strings.TrimSpace(string(out)))
	}
	return nil
}
